spring:
#  profiles:
#    active: dev
  devtools:
    add-properties: true
  sendgrid:
    api-key: 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
    from-email: duynguyencoder154@gmail.com

